### ISSUE TITLE
Move coverage configuration to pyproject.toml

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/pypim#64]
💡 **Idea**
Configuration for tools such as `black` and `isort` is already declared in the `pyproject.toml` file. The same can be done for the `.coveragerc` file. An example from `ansys-templates`:

```toml
[tool.coverage.run]
source = ["ansys/templates"]
omit = ["ansys/templates/python/*"]

[tool.coverage.report]
show_missing = true
```
